### ISSUE TITLE
[install-autoshutdown-server-extension] ValueError: Python version 3.10 unsupported

### ISSUE THREAD

**Issue by anthonydandrea** [aws-samples/sagemaker-studio-lifecycle-config-examples#38]
When executing the script [on-jupyter-server-start.sh](https://github.com/aws-samples/sagemaker-studio-lifecycle-config-examples/blob/main/scripts/install-autoshutdown-server-extension/on-jupyter-server-start.sh) in Sagemaker Studio (which installs [sagemaker_studio_autoshutdown-0.1.5](https://github.com/aws-samples/sagemaker-studio-auto-shutdown-extension/raw/main/sagemaker_studio_autoshutdown-0.1.5.tar.gz)), I get the following error in my `LifecycleConfigOnStart` logs:

```
Obtaining file:///home/.auto-shutdown/sagemaker_studio_autoshutdown-0.1.5
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 181, in prepare_metadata_for_build_editable
          return hook(metadata_directory, config_settings)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/build_meta.py", line 454, in prepare_metadata_for_build_editable
          return self.prepare_metadata_for_build_wheel(
        File "/opt/conda/lib/python3.10/site-packages/setuptools/build_meta.py", line 380, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/opt/conda/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 732, in <module>
        File "<string>", line 113, in ensure_python
      ValueError: Python version 3.10 unsupported
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
```

Does the package need to be updated to accept Python 3.10 environments? The `pyproject.toml` of the `sagemaker_studio_autoshutdown-0.1.5` module does not list 3.10 and I'm wondering if adding that will resolve this problem.

**Comment by anthonydandrea** [comment]
Closing to open in repo hosting `sagemaker_studio_autoshutdown-0.1.5`: https://github.com/aws-samples/sagemaker-studio-auto-shutdown-extension/issues/50
